using System;
using System.Collections.Generic;
using UnityEngine;


namespace ShaderFactory.CozyGraphToolkit.Runtime
{
    /// <summary>
    /// Represents a node after being converted to runtime form.
    /// This runtime version of the node is what gets saved in the .cozygraph asset file.
    /// It is also the version that evaluates ports and executes in-game runtime logic
    /// </summary>
    [Serializable]
    public class RuntimeCozyNode 
    {
        /// <summary> Node's unique identifier (generated by the importer with a new GUID each time). </summary>
        public string NodeID;

        /// <summary> Identifies editor node class name. </summary>
        public string NodeType;

        /// <summary> Unique identifier of the node this node's output connects to. </summary>
        public string NextNodeID;

        /// <summary> Stores all input port values using a class that is serializable </summary>
        [SerializeReference] public List<CozyRuntimePort> InputPorts = new ();

        /// <summary> Stores all input port values using a class that is serializable </summary>
        [SerializeReference] public List<CozyRuntimePort> OutputPorts = new ();

        /// <summary> Reference to what runtime graph this node is a part of. </summary>
        [SerializeReference] public RuntimeCozyGraph Graph;

        #region Constructors
        public RuntimeCozyNode() {}

        /// <summary> Default constructor. Instances of RuntimeCozyNodes are created by the importer (CozyGraphI </summary>
        public RuntimeCozyNode(string _nodeID, string _nodeType, RuntimeCozyGraph _graph)
        {
            NodeID = _nodeID;
            NodeType = _nodeType;
            Graph = _graph;
        }
        #endregion

        /// <summary> Evaluate an output of a specific port. </summary>
        public virtual object GetValue(CozyRuntimePort port)
        {
            foreach (CozyRuntimePort p in InputPorts)
            {
                Debug.Log($"Looking at port {p}");
            }
            return null;
        }

        /// <summary> Execute Logic if applicable. </summary>
        public virtual object Run()
        {
            Debug.Log("No Run() override.");
            return null;
        }

        /// <summary> Create a CozyRuntimePort entry to the list. </summary>
        public void RegisterPort (string key, object value, bool _isOutput)
        {
            foreach (var p in InputPorts)   // If exists, just replace the value..
            {
                if (p.Key == key)
                    p.SetValue(value);
                    return;
            }
            
            CozyRuntimePort entry = new (); // But if not, create a new entry.
            entry.Key = key;
            entry.SetValue(value);
            InputPorts.Add(entry);
        }

        public CozyRuntimePort GetPortByName(string key)
        {
            foreach (var port in InputPorts)
            {
                if (port.Key == key)
                { 
                    return port;
                }
            }
            Debug.LogError($"GetPortByName failed to find port named '{key}'");
            return null;
        }
    }

    [Serializable]
    public class ConnectedPortAddress
    {
        public RuntimeCozyNode node;
        public string portName;
        public bool isOutput;

        public ConnectedPortAddress(RuntimeCozyNode _node, string _portName, bool _isOutput)
        {
            node = _node;
            portName = _portName;
            isOutput = _isOutput;
        }
    }

}