using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using ShaderFactory.CozyGraphToolkit.Runtime;
using UnityEditor;
using UnityEngine;

namespace ShaderFactory.CozyGraphToolkit.Editor
{
    /// <summary>
    /// Generates small editor-only adapters for game-authored CozyNode classes.
    ///
    /// Graph Toolkit's native item library discovers concrete editor Node types
    /// at compile time. A CozyNode deliberately stays in a runtime assembly, so
    /// this generator bridges the two assemblies without asking game developers
    /// to write a second class or to reference UnityEditor themselves.
    /// </summary>
    [InitializeOnLoad]
    internal static class CozyNodeAdapterGenerator
    {
        private const string GeneratedFolderAssetPath = "Assets/CozyNodes.Generated/Editor";
        private const string GeneratedFileName = "CozyNodeAdapters.g.cs";
        private const string GeneratedNamespace = "ShaderFactory.CozyGraphToolkit.Generated";

        private static bool generationQueued;

        static CozyNodeAdapterGenerator()
        {
            ScheduleGeneration();
        }

        /// <summary>
        /// Queues one generation pass after Unity is ready to inspect loaded
        /// assemblies. Repeated asset imports share the same queued pass.
        /// </summary>
        internal static void ScheduleGeneration()
        {
            if (generationQueued)
                return;

            generationQueued = true;
            EditorApplication.delayCall += GenerateWhenUnityIsReady;
        }

        /// <summary>
        /// Keeps generated code from scheduling a redundant generation pass when
        /// Unity imports the file that this generator just wrote.
        /// </summary>
        internal static bool IsGeneratedAssetPath(string assetPath)
        {
            return assetPath.StartsWith(GeneratedFolderAssetPath, StringComparison.Ordinal);
        }

        private static void GenerateWhenUnityIsReady()
        {
            generationQueued = false;

            if (EditorApplication.isCompiling || EditorApplication.isUpdating)
            {
                ScheduleGeneration();
                return;
            }

            GenerateAdapters();
        }

        private static void GenerateAdapters()
        {
            List<Type> nodeTypes = FindSupportedNodeTypes();
            string generatedSource = BuildSource(nodeTypes);
            string generatedFilePath = GetGeneratedFilePath();

            Directory.CreateDirectory(Path.GetDirectoryName(generatedFilePath));

            if (File.Exists(generatedFilePath) &&
                File.ReadAllText(generatedFilePath) == generatedSource)
            {
                return;
            }

            File.WriteAllText(generatedFilePath, generatedSource, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(GetGeneratedFileAssetPath());
        }

        private static List<Type> FindSupportedNodeTypes()
        {
            List<Type> nodeTypes = new List<Type>();

            foreach (Type nodeType in TypeCache.GetTypesDerivedFrom<CozyNode>())
            {
                if (!IsSupportedNodeType(nodeType))
                    continue;

                nodeTypes.Add(nodeType);
            }

            nodeTypes.Sort((firstType, secondType) => string.Compare(
                firstType.AssemblyQualifiedName,
                secondType.AssemblyQualifiedName,
                StringComparison.Ordinal));

            return nodeTypes;
        }

        private static bool IsSupportedNodeType(Type nodeType)
        {
            if (nodeType == null || nodeType.IsAbstract || nodeType.IsGenericTypeDefinition ||
                nodeType.ContainsGenericParameters)
            {
                return false;
            }

            // The generated source lives in the project's Editor assembly, so it
            // must be able to reference the game type directly.
            if (!nodeType.IsVisible)
            {
                Debug.LogWarning(
                    $"Cozy Nodes cannot add '{nodeType.FullName}' to the native " +
                    "node menu because the class is not public.");
                return false;
            }

            if (nodeType.GetConstructor(Type.EmptyTypes) == null)
            {
                Debug.LogWarning(
                    $"Cozy Nodes cannot add '{nodeType.FullName}' to the native " +
                    "node menu because it needs a public parameterless constructor.");
                return false;
            }

            return true;
        }

        private static string BuildSource(List<Type> nodeTypes)
        {
            StringBuilder source = new StringBuilder();
            source.AppendLine("// <auto-generated>");
            source.AppendLine("// This file is generated by Cozy Nodes. Do not edit it manually.");
            source.AppendLine("// </auto-generated>");
            source.AppendLine();
            source.AppendLine("using System;");
            source.AppendLine("using ShaderFactory.CozyGraphToolkit.Editor;");
            source.AppendLine("using Unity.GraphToolkit.Editor;");
            source.AppendLine();
            source.AppendLine("namespace " + GeneratedNamespace);
            source.AppendLine("{");

            foreach (Type nodeType in nodeTypes)
                AppendAdapter(source, nodeType);

            source.AppendLine("}");
            return source.ToString();
        }

        private static void AppendAdapter(StringBuilder source, Type nodeType)
        {
            CozyNodeDefinition definition = CozyNodeReflection.GetDefinition(nodeType);
            string category = "Cozy Nodes/" +
                              (string.IsNullOrWhiteSpace(definition.Category)
                                  ? "Game Nodes"
                                  : definition.Category);
            string className = "CozyNodeAdapter_" + GetStableIdentifier(nodeType);

            source.AppendLine("    [Serializable]");
            // Generated adapters compile into the game's Editor assembly, while
            // CozyGraph lives in the package's Editor assembly. Graph Toolkit
            // requires this public attribute to include cross-assembly nodes in
            // CozyGraph's native right-click item library.
            source.AppendLine("    [UseWithGraph(typeof(CozyGraph))]");
            source.AppendLine(
                "    [Node(\"" + EscapeString(category) + "\", null, \"" +
                EscapeString(definition.Title) + "\")]");
            source.AppendLine("    public sealed class " + className + " : CustomCozyNode");
            source.AppendLine("    {");
            source.AppendLine("        protected override Type GetCustomNodeType()");
            source.AppendLine("        {");
            source.AppendLine("            return typeof(" + GetSourceTypeName(nodeType) + ");");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine();
        }

        private static string GetStableIdentifier(Type nodeType)
        {
            string typeName = nodeType.AssemblyQualifiedName;
            uint hash = 2166136261;

            for (int characterIndex = 0; characterIndex < typeName.Length; characterIndex++)
            {
                hash ^= typeName[characterIndex];
                hash *= 16777619;
            }

            return hash.ToString("X8");
        }

        private static string GetSourceTypeName(Type nodeType)
        {
            return "global::" + nodeType.FullName.Replace("+", ".");
        }

        private static string EscapeString(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string GetGeneratedFilePath()
        {
            return Path.Combine(Application.dataPath, "CozyNodes.Generated", "Editor", GeneratedFileName);
        }

        private static string GetGeneratedFileAssetPath()
        {
            return GeneratedFolderAssetPath + "/" + GeneratedFileName;
        }
    }

    /// <summary>
    /// Regenerates adapters when game scripts change. The generated file is
    /// ignored as a trigger because generation writes only when its contents
    /// actually changed, preventing a recompilation loop.
    /// </summary>
    internal class CozyNodeAdapterGeneratorPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (ContainsScriptChangeOutsideGeneratedFolder(importedAssets) ||
                ContainsScriptChangeOutsideGeneratedFolder(deletedAssets) ||
                ContainsScriptChangeOutsideGeneratedFolder(movedAssets) ||
                ContainsScriptChangeOutsideGeneratedFolder(movedFromAssetPaths))
            {
                CozyNodeAdapterGenerator.ScheduleGeneration();
            }
        }

        private static bool ContainsScriptChangeOutsideGeneratedFolder(string[] assetPaths)
        {
            foreach (string assetPath in assetPaths)
            {
                if (!assetPath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
                    continue;

                if (CozyNodeAdapterGenerator.IsGeneratedAssetPath(assetPath))
                    continue;

                return true;
            }

            return false;
        }
    }
}
